//! Conversation state: in-memory shape of a persisted thread.
//!
//! `ConversationState` is the runtime view of `conversation_turns` rows.
//! It feeds the planner (`to_chat_messages`) and is reconstructed from
//! storage on cache miss or restart.

use n3ur0n_core::InstanceId;
use n3ur0n_storage::Db;
use n3ur0n_storage::conversations::{self, ConversationRecord, TurnRecord};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use thiserror::Error;
use time::OffsetDateTime;
use uuid::Uuid;

/// Errors specific to conversation state load / persist.
#[derive(Debug, Error)]
pub enum ConversationError {
    #[error("storage: {0}")]
    Storage(#[from] n3ur0n_storage::StorageError),

    #[error("serde: {0}")]
    Serde(#[from] serde_json::Error),

    #[error("conversation not found: {0}")]
    NotFound(String),

    #[error("ownership mismatch")]
    OwnershipMismatch,
}

pub type ConversationResult<T> = Result<T, ConversationError>;

/// File attached to a user message (blob protocol class D → A on send).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct UserAttachment {
    pub hash: String,
    pub mime: String,
    pub size: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Incoming user message from the conversations API.
#[derive(Debug, Clone, Default)]
pub struct UserInput {
    pub text: String,
    pub attachments: Vec<UserAttachment>,
}

impl From<String> for UserInput {
    fn from(text: String) -> Self {
        Self {
            text,
            attachments: Vec::new(),
        }
    }
}

impl From<&str> for UserInput {
    fn from(text: &str) -> Self {
        Self {
            text: text.to_string(),
            attachments: Vec::new(),
        }
    }
}

impl UserInput {
    pub fn is_empty(&self) -> bool {
        self.text.trim().is_empty() && self.attachments.is_empty()
    }

    /// Text passed to the planner / LLM (attachments summarised inline).
    pub fn planner_text(&self) -> String {
        let mut text = self.text.trim().to_string();
        if text.is_empty() && !self.attachments.is_empty() {
            text = format!("The user sent {} file(s).", self.attachments.len());
        }
        for att in &self.attachments {
            let label = att.name.as_deref().unwrap_or(&att.mime);
            text.push_str(&format!(
                "\n[attachment: {label} · {} · {} bytes]",
                att.hash, att.size
            ));
        }
        text
    }
}

/// One step in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "snake_case")]
pub enum Turn {
    User {
        content: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        attachments: Vec<UserAttachment>,
        ts: i64,
    },
    Assistant {
        content: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        ts: i64,
    },
    ToolCall {
        /// Free-form id linking to its result. Generated by the planner.
        id: String,
        peer_id: InstanceId,
        capability: String,
        args: Value,
        ts: i64,
    },
    ToolResult {
        /// Matches the `id` of its `ToolCall`.
        call_id: String,
        peer_id: InstanceId,
        capability: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        result: Option<Value>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<String>,
        ts: i64,
    },
    System {
        content: String,
        ts: i64,
    },
}

impl Turn {
    pub fn role_label(&self) -> &'static str {
        match self {
            Turn::User { .. } => "user",
            Turn::Assistant { .. } => "assistant",
            Turn::ToolCall { .. } => "tool_call",
            Turn::ToolResult { .. } => "tool_result",
            Turn::System { .. } => "system",
        }
    }

    pub fn ts(&self) -> i64 {
        match self {
            Turn::User { ts, .. }
            | Turn::Assistant { ts, .. }
            | Turn::ToolCall { ts, .. }
            | Turn::ToolResult { ts, .. }
            | Turn::System { ts, .. } => *ts,
        }
    }
}

/// In-memory runtime view of a conversation.
#[derive(Debug, Clone)]
pub struct ConversationState {
    pub id: String,
    pub client_id: String,
    pub title: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub turns: Vec<Turn>,
    /// Highest `seq` currently persisted; the next append uses `next_seq + 1`.
    next_seq: i64,
}

impl ConversationState {
    pub fn new(id: String, client_id: String, title: Option<String>) -> Self {
        let now = OffsetDateTime::now_utc().unix_timestamp();
        Self {
            id,
            client_id,
            title,
            created_at: now,
            updated_at: now,
            turns: Vec::new(),
            next_seq: 0,
        }
    }

    pub fn next_seq(&self) -> i64 {
        self.next_seq + 1
    }

    /// Append a turn in memory and bookkeep `next_seq`.
    pub fn push(&mut self, turn: Turn) {
        self.next_seq += 1;
        self.updated_at = turn.ts();
        self.turns.push(turn);
    }

    /// Record a User turn (text only).
    pub fn push_user(&mut self, content: impl Into<String>) -> &Turn {
        self.push_user_input(&UserInput {
            text: content.into(),
            attachments: Vec::new(),
        })
    }

    /// Record a User turn with optional attachments.
    pub fn push_user_input(&mut self, input: &UserInput) -> &Turn {
        let ts = OffsetDateTime::now_utc().unix_timestamp();
        self.push(Turn::User {
            content: input.text.clone(),
            attachments: input.attachments.clone(),
            ts,
        });
        self.turns.last().expect("just pushed")
    }

    /// Record an Assistant turn.
    pub fn push_assistant(&mut self, content: String, model: Option<String>) -> &Turn {
        let ts = OffsetDateTime::now_utc().unix_timestamp();
        self.push(Turn::Assistant { content, model, ts });
        self.turns.last().expect("just pushed")
    }

    /// Record a ToolCall and return its generated id.
    pub fn push_tool_call(
        &mut self,
        peer_id: InstanceId,
        capability: String,
        args: Value,
    ) -> String {
        let id = format!("call_{}", Uuid::new_v4().simple());
        self.push_tool_call_with_id(id.clone(), peer_id, capability, args);
        id
    }

    /// Record a ToolCall reusing a caller-provided id. Used when the plan
    /// executor already minted the id (so the in-memory turn and the row it
    /// persisted incrementally to the DB share the same `call_id`).
    pub fn push_tool_call_with_id(
        &mut self,
        id: String,
        peer_id: InstanceId,
        capability: String,
        args: Value,
    ) {
        let ts = OffsetDateTime::now_utc().unix_timestamp();
        self.push(Turn::ToolCall {
            id,
            peer_id,
            capability,
            args,
            ts,
        });
    }

    pub fn push_tool_result(
        &mut self,
        call_id: String,
        peer_id: InstanceId,
        capability: String,
        result: Option<Value>,
        error: Option<String>,
    ) {
        let ts = OffsetDateTime::now_utc().unix_timestamp();
        self.push(Turn::ToolResult {
            call_id,
            peer_id,
            capability,
            result,
            error,
            ts,
        });
    }

    pub fn push_system(&mut self, content: String) {
        let ts = OffsetDateTime::now_utc().unix_timestamp();
        self.push(Turn::System { content, ts });
    }

    /// Convert turns to OpenAI-style chat messages, applying:
    /// 1. Visibility filter: hide ToolCall/ToolResult turns that belong to a
    ///    completed dispatch (i.e. happened before the most recent Assistant
    ///    turn). The planner sees a clean User/Assistant trail for past
    ///    rounds; tool turns from the **current** dispatch (after the most
    ///    recent Assistant) stay visible so the planner can iterate.
    ///    Without this, llama3.1:8b and similar imitate past tool_call
    ///    formats inside their content output, producing JSON garbage.
    /// 2. Context window pruning: keep at most `max_turns`, never split a
    ///    ToolCall/ToolResult pair.
    pub fn to_chat_messages(&self, max_turns: usize) -> Vec<Value> {
        let visible = filter_visible_for_llm(&self.turns);
        let pruned = prune_context_refs(&visible, max_turns);
        pruned.into_iter().map(turn_to_message).collect()
    }

    /// Turns expected by the UI (raw representation).
    pub fn ui_turns(&self) -> Vec<Value> {
        self.turns
            .iter()
            .map(|t| serde_json::to_value(t).expect("Turn serialises"))
            .collect()
    }

    /// Dangling tool_call recovery: if the last turn is a ToolCall without a
    /// paired ToolResult, inject a synthetic ToolResult error so the planner
    /// sees a coherent state on resume after a crash.
    pub fn validate(&mut self) {
        let needs_repair = matches!(self.turns.last(), Some(Turn::ToolCall { .. }));
        if needs_repair
            && let Some(Turn::ToolCall {
                id,
                peer_id,
                capability,
                ..
            }) = self.turns.last().cloned()
        {
            self.push_tool_result(
                id,
                peer_id,
                capability,
                None,
                Some("instance restarted before result was persisted".into()),
            );
        }
    }
}

/// Convert a Turn to an OpenAI-shaped chat message.
///
/// Tool names use the **short peer prefix** (12 chars after `n3:`) to match
/// what the planner advertises in its `tools` array. Mixing full and short
/// peer ids inside the same conversation confuses LLMs.
fn turn_to_message(turn: &Turn) -> Value {
    match turn {
        Turn::User { content, .. } => json!({"role": "user", "content": content}),
        Turn::Assistant { content, .. } => json!({"role": "assistant", "content": content}),
        Turn::System { content, .. } => json!({"role": "system", "content": content}),
        Turn::ToolCall {
            id,
            peer_id,
            capability,
            args,
            ..
        } => json!({
            "role": "assistant",
            "content": Value::Null,
            "tool_calls": [{
                "id": id,
                "type": "function",
                "function": {
                    "name": tool_name(peer_id.as_str(), capability),
                    "arguments": serde_json::to_string(args).unwrap_or_else(|_| "{}".into())
                }
            }]
        }),
        Turn::ToolResult {
            call_id,
            result,
            error,
            ..
        } => {
            let content = if let Some(err) = error {
                json!({"error": err}).to_string()
            } else {
                serde_json::to_string(result.as_ref().unwrap_or(&Value::Null))
                    .unwrap_or_else(|_| "null".into())
            };
            json!({
                "role": "tool",
                "tool_call_id": call_id,
                "content": content
            })
        }
    }
}

/// Tool name advertised to the LLM. Must match `Catalog::tool_name`.
pub(crate) fn tool_name(peer_id: &str, capability: &str) -> String {
    let trimmed = peer_id.strip_prefix("n3:").unwrap_or(peer_id);
    let short: String = trimmed.chars().take(12).collect();
    format!("{short}::{capability}")
}

/// Prune context: keep at most `max_turns` from the tail, never splitting a
/// ToolCall / ToolResult pair. v0.1: doesn't preserve leading systems
/// separately — system prompts are injected fresh by the planner at each
/// dispatch, so only persisted Turns matter here.
pub(crate) fn prune_context_refs<'a>(refs: &[&'a Turn], max_turns: usize) -> Vec<&'a Turn> {
    if refs.len() <= max_turns {
        return refs.to_vec();
    }
    let mut start = refs.len() - max_turns;
    // If we'd start at a ToolResult whose ToolCall is just outside, rewind.
    if start > 0
        && let Some(Turn::ToolResult { call_id, .. }) = refs.get(start).copied()
        && matches!(refs.get(start - 1).copied(), Some(Turn::ToolCall { id, .. }) if id == call_id)
    {
        start -= 1;
    }
    refs[start..].to_vec()
}

/// Hide ToolCall/ToolResult turns that belong to a **completed** dispatch.
/// A dispatch is "completed" when an Assistant turn closes it.
///
/// Why: when the LLM sees prior tool_calls in its history, it tends to
/// imitate them in raw text content on subsequent turns (observed with
/// llama3.1:8b after a chat tool exchange). Hiding them yields a clean
/// User/Assistant trail for past rounds while keeping the tool turns of
/// the **current** dispatch (those after the most recent Assistant)
/// visible so the planner can iterate.
pub(crate) fn filter_visible_for_llm(turns: &[Turn]) -> Vec<&Turn> {
    let last_assistant_idx = turns
        .iter()
        .enumerate()
        .rev()
        .find(|(_, t)| matches!(t, Turn::Assistant { .. }))
        .map(|(i, _)| i);

    turns
        .iter()
        .enumerate()
        .filter_map(|(i, t)| {
            let is_tool = matches!(t, Turn::ToolCall { .. } | Turn::ToolResult { .. });
            let is_past = last_assistant_idx.map(|li| i <= li).unwrap_or(false);
            if is_tool && is_past { None } else { Some(t) }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Persistence helpers
// ---------------------------------------------------------------------------

/// Create a fresh conversation row + return the new state.
pub fn create(
    db: &Db,
    client_id: &str,
    title: Option<String>,
) -> ConversationResult<ConversationState> {
    let id = format!("conv_{}", Uuid::new_v4().simple());
    let state = ConversationState::new(id.clone(), client_id.to_string(), title.clone());
    conversations::insert(
        db,
        &ConversationRecord {
            id,
            client_id: client_id.to_string(),
            title,
            created_at: state.created_at,
            updated_at: state.updated_at,
        },
    )?;
    Ok(state)
}

/// Load conversation header + all turns, verify ownership, run validate().
pub fn load(db: &Db, id: &str, client_id: &str) -> ConversationResult<ConversationState> {
    let record =
        conversations::get(db, id)?.ok_or_else(|| ConversationError::NotFound(id.to_string()))?;
    if record.client_id != client_id {
        return Err(ConversationError::OwnershipMismatch);
    }
    let raw = conversations::load_turns(db, id)?;
    let mut turns = Vec::with_capacity(raw.len());
    let mut max_seq = 0;
    for r in raw {
        let turn: Turn = serde_json::from_str(&r.payload)?;
        turns.push(turn);
        if r.seq > max_seq {
            max_seq = r.seq;
        }
    }
    let mut state = ConversationState {
        id: record.id,
        client_id: record.client_id,
        title: record.title,
        created_at: record.created_at,
        updated_at: record.updated_at,
        turns,
        next_seq: max_seq,
    };
    state.validate();
    Ok(state)
}

/// Persist the most recently appended turn.
pub fn persist_last(db: &Db, state: &ConversationState) -> ConversationResult<()> {
    let last_idx = state
        .turns
        .len()
        .checked_sub(1)
        .ok_or_else(|| ConversationError::NotFound("empty turns".into()))?;
    let turn = &state.turns[last_idx];
    let payload = serde_json::to_string(turn)?;
    conversations::append_turn(
        db,
        &TurnRecord {
            conversation_id: state.id.clone(),
            seq: state.next_seq, // already incremented at push()
            role: turn.role_label().to_string(),
            payload,
            created_at: turn.ts(),
        },
        state.updated_at,
    )?;
    Ok(())
}

/// Persist one (ToolCall, ToolResult) pair directly to the DB at a seq
/// reserved by the step's plan index — without touching any in-memory
/// `ConversationState`. Used by the plan executor's durability hook so each
/// step's turns hit storage the moment it completes; a crash mid-run then
/// leaves a partial but correctly-ordered trace.
///
/// `base_seq` is the user turn's seq. Step `plan_index` claims
/// `base_seq + 1 + 2*plan_index` for its call and the next seq for its result,
/// matching the order an in-memory replay (user turn, then tool pairs in plan
/// order) would assign.
#[allow(clippy::too_many_arguments)]
pub fn persist_tool_pair_at(
    db: &Db,
    conversation_id: &str,
    base_seq: i64,
    plan_index: usize,
    call_id: &str,
    peer_id: &InstanceId,
    capability: &str,
    args: &Value,
    result: &Option<Value>,
    error: &Option<String>,
    updated_at: i64,
) -> ConversationResult<()> {
    let call_seq = base_seq + 1 + 2 * plan_index as i64;
    let result_seq = call_seq + 1;
    let call = Turn::ToolCall {
        id: call_id.to_string(),
        peer_id: peer_id.clone(),
        capability: capability.to_string(),
        args: args.clone(),
        ts: updated_at,
    };
    let res = Turn::ToolResult {
        call_id: call_id.to_string(),
        peer_id: peer_id.clone(),
        capability: capability.to_string(),
        result: result.clone(),
        error: error.clone(),
        ts: updated_at,
    };
    for (seq, turn) in [(call_seq, call), (result_seq, res)] {
        let payload = serde_json::to_string(&turn)?;
        conversations::append_turn(
            db,
            &TurnRecord {
                conversation_id: conversation_id.to_string(),
                seq,
                role: turn.role_label().to_string(),
                payload,
                created_at: updated_at,
            },
            updated_at,
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use n3ur0n_core::Keypair;
    use n3ur0n_storage::open_in_memory;

    fn id() -> InstanceId {
        Keypair::generate().instance_id()
    }

    #[test]
    fn create_load_round_trip() {
        let db = open_in_memory().unwrap();
        let mut state = create(&db, "alice", Some("hello".into())).unwrap();
        state.push_user("hi");
        persist_last(&db, &state).unwrap();
        state.push_assistant("hey there".into(), Some("test-model".into()));
        persist_last(&db, &state).unwrap();

        let reloaded = load(&db, &state.id, "alice").unwrap();
        assert_eq!(reloaded.turns.len(), 2);
        assert_eq!(reloaded.next_seq, 2);
    }

    #[test]
    fn ownership_mismatch_rejected() {
        let db = open_in_memory().unwrap();
        let state = create(&db, "alice", None).unwrap();
        let err = load(&db, &state.id, "bob").unwrap_err();
        matches!(err, ConversationError::OwnershipMismatch);
    }

    #[test]
    fn validate_repairs_dangling_tool_call() {
        let db = open_in_memory().unwrap();
        let mut state = create(&db, "alice", None).unwrap();
        state.push_user("call something");
        persist_last(&db, &state).unwrap();
        let _call_id = state.push_tool_call(id(), "echo".into(), json!({}));
        persist_last(&db, &state).unwrap();
        // Don't persist a tool_result — simulate crash.

        let reloaded = load(&db, &state.id, "alice").unwrap();
        // validate() must have appended a synthetic ToolResult.
        assert!(matches!(
            reloaded.turns.last(),
            Some(Turn::ToolResult { error: Some(_), .. })
        ));
    }

    #[test]
    fn pruning_keeps_pairs() {
        let peer = id();
        let mut state = ConversationState::new("c".into(), "alice".into(), None);
        state.push_user("hi");
        let cid = state.push_tool_call(peer.clone(), "x".into(), json!({}));
        state.push_tool_result(cid, peer, "x".into(), Some(json!("ok")), None);
        state.push_assistant("done".into(), None);
        // 4 turns; ask for 2.
        let pruned = state.to_chat_messages(2);
        // Should keep the last 2, both atomic.
        assert!(!pruned.is_empty());
    }

    #[test]
    fn to_chat_messages_emits_tool_messages_during_current_dispatch() {
        // Mid-dispatch: User just pushed, ToolCall + ToolResult appended,
        // no Assistant yet. The LLM must still see the tool_call/result it
        // just executed.
        let peer = id();
        let mut state = ConversationState::new("c".into(), "alice".into(), None);
        state.push_user("u1");
        let cid = state.push_tool_call(peer.clone(), "echo".into(), json!({"x": 1}));
        state.push_tool_result(cid, peer, "echo".into(), Some(json!({"x": 1})), None);
        let msgs = state.to_chat_messages(10);
        let roles: Vec<&str> = msgs.iter().map(|m| m["role"].as_str().unwrap()).collect();
        assert_eq!(roles, ["user", "assistant", "tool"]); // tool_call as assistant + tool_result as tool
    }

    #[test]
    fn past_dispatch_tool_turns_filtered_out() {
        // After Assistant closes a dispatch, its tool_call/tool_result
        // become invisible to subsequent LLM iterations.
        let peer = id();
        let mut state = ConversationState::new("c".into(), "alice".into(), None);
        state.push_user("u1");
        let cid = state.push_tool_call(peer.clone(), "echo".into(), json!({"x": 1}));
        state.push_tool_result(cid, peer, "echo".into(), Some(json!({"x": 1})), None);
        state.push_assistant("first reply".into(), None);
        state.push_user("u2");
        // Mid-second-dispatch: no new tool_call yet.
        let msgs = state.to_chat_messages(10);
        let roles: Vec<&str> = msgs.iter().map(|m| m["role"].as_str().unwrap()).collect();
        // Past dispatch's tool_call+tool_result hidden. Past User+Assistant
        // kept. Current dispatch's User kept.
        assert_eq!(roles, ["user", "assistant", "user"]);
    }

    #[test]
    fn tool_name_uses_short_peer_format() {
        let peer = InstanceId::parse("n3:abcdef1234567890longerthantwelvechars")
            .unwrap_or_else(|_| Keypair::generate().instance_id());
        let mut state = ConversationState::new("c".into(), "alice".into(), None);
        state.push_user("u1");
        let cid = state.push_tool_call(peer.clone(), "chat".into(), json!({}));
        state.push_tool_result(cid, peer, "chat".into(), Some(json!("ok")), None);
        let msgs = state.to_chat_messages(10);
        // The middle message is the tool_call rendered as assistant + tool_calls.
        let tc = &msgs[1]["tool_calls"][0]["function"]["name"];
        let name = tc.as_str().unwrap();
        assert!(!name.starts_with("n3:"));
        assert!(name.ends_with("::chat"));
        // Short part = 12 chars max.
        let prefix = name.split("::").next().unwrap();
        assert!(prefix.len() <= 12);
    }
}
